version: "3.8"

services:
  blazor_app:
    build:
      context: ./BlazorPythonModelsPresentation
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - python_api

  python_api:
    build:
      context: ./WaterModels
      dockerfile: Dockerfile
    ports:
      - "5000:5000"